spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cypherdigitaltwin}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Can be 'create', 'create-drop', 'update', or 'none'
    properties:
      hibernate:
        #dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
    show-sql: true
    open-in-view: false

